server:
  port: 8082
  servlet:
    context-path: /kardex/v1/

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store_db?currentSchema=store
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  file:
    path: ./logs
  level:
    org:
      hibernate:
        SQL: debug

# Eureka client configuration

management:
  endpoints:
    info:
      env:
        enabled: true
    web:
      exposure:
        include: '*'
        base-path: /actuator
